### ISSUE TITLE
Proj: Workshop on Plandex/Aider

### ISSUE THREAD

**Issue by g-simmons** [g-simmons/llm_persona_website#10]
@wuyudaxia let me know what you think of this! This is not mandatory but I think it would be really beneficial for the group.

## Background
*relevant information and motivation for this task*

[Plandex](https://github.com/plandex-ai/plandex) and [Aider](https://github.com/Aider-AI/aider) are two LLM-based tools, used for "AI pair programming".

I've found Plandex to be useful for multi-file changes to implement relatively straightforward new features.

These tools fill a gap where:
- Traditional find-and-replace is not flexible enough
- Copy-and-pasting between Claude/ChatGPT chat and the IDE is cumbersome
  - This is often due to having to make simultaneous changes to several files
- VSCode Cmd-I or Cursor Cmd-K is tedious or error-prone
  - This is also often due to having to make simultaneous changes to several files

I think these tools could be useful for research work. I've encouraged students to try them, but I think due to learning curve or some other factors the tools haven't stuck.

## Task
*high-level task description*
For one of our journal club meetings, hold a workshop where students participate in a step-by-step tutorial to learn how to use Plandex/Aider/similar.

## How To
*specific guidance on implementation*

I have used Plandex myself, I would prefer to learn about Aider for comparsion. But either is fine.

Workshop should include things like:

- Setting up the tool, including API key
- Setting up or cloning a prepared toy repository
- Scoping a task in the toy repository
- Using one of the tools to work on the task

## Undecided
*implementation details that haven't been decided yet ("known-unknown" status)*

There are other things to cover:
- Choosing which model pack to use ("model pack" is terminology from Plandex, not sure what the Aider equivalent is)
- Comparing and contrasting tools
- Describing gotchas and how to overcome them
- When not to use this tool
- How this workflow compares to other workflows like VSCode Cmd-I

## Expected Results
*what results are expected from completing this issue*
### Writing

**Comment by wuyudaxia** [comment]
Hi! I think this would be great for performing a workshop to do so, since there is a gap between the latest tech-development and the knowledge we learned in school, and holding a workshop about learning how to use tools would be so nice.

I really appreciate you for encourage student to use these tools, and tell them when now to use. I think this workshop would be beneficial for most of the students who will have to code for their projects, especially for those who have not really have use and install the tools like this

**Comment by g-simmons** [comment]
@wuyudaxia Awesome, have you started work on this? @AbhiramBorra can take the lead on this if you haven't started already. Please get in touch to coordinate :)

- [ ] Decide a date for the Plandex/Aider workshop
- [ ] Put slides/presentation content together
- [ ] Announce the workshop

**Comment by wuyudaxia** [comment]
Sounds good! I am sorry for not replying in time, I would be happy to coordinate!

**Comment by g-simmons** [comment]
No worries!

Another tool you might consider for the workshop, recently got SOTA performance on SWEBench-Verified https://docs.all-hands.dev/modules/usage/getting-started
